name: spotify
description: "A new Flutter project."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.4.1 <4.0.0"

dependencies:
  bloc: ^8.1.4
  cloud_firestore: ^4.14.0
  cupertino_icons: ^1.0.6
  dartz: ^0.10.1
  firebase_auth: ^4.16.0
  firebase_core: ^2.24.2
  firebase_database: ^10.4.0
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.6
  flutter_svg: ^2.0.7
  get_it: ^7.7.0
  go_router: ^14.2.0
  google_maps_flutter: ^2.9.0
  hydrated_bloc: ^9.1.5
  path_provider: ^2.1.4

dev_dependencies:
  flutter_launcher_icons: "^0.13.1"
  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/logo.png"
  min_sdk_android: 21

flutter:
  uses-material-design: true

  assets:
    - assets/vectors/
    - assets/fonts/
    - assets/images/

  fonts:
    - family: Satoshi
      fonts:
        - asset: assets/fonts/Satoshi-Regular.ttf
          weight: 400
        - asset: assets/fonts/Satoshi-Medium.ttf
          weight: 500
        - asset: assets/fonts/Satoshi-Bold.ttf
          weight: 600
        - asset: assets/fonts/Satoshi-Black.ttf
          weight: 900
        - asset: assets/fonts/Satoshi-Light.ttf
          weight: 300
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
